// *** SETTINGS ***
export const USER_SETTINGS_UPDATE_LANGUAGE = "USER_SETTINGS_UPDATE_LANGUAGE";

//** BACKEND ***
export const BACK_END_UPDATE_STATUS = "BACK_END_UPDATE_STATUS";

//*** USER GUILDS ***
export const USER_GUILDS_UPDATE = "USER_GUILDS_UPDATE";

//*** USER GEARS */
export const USER_GEAR_UPDATE = "USER_GEAR_UPDATE";

//** CONFIGURATION */
export const CONFIG_BATTLEMODE_UPDATE = "CONFIG_BATTLEMODE_UPDATE";
export const CONFIG_CLASS_UPDATE = "CONFIG_CLASS_UPDATE";
export const CONFIG_TRINA_UPDATE = "CONFIG_TRINA_UPDATE";
